name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Projeyi al
        uses: actions/checkout@v4

      - name: Java kur
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Gradle ile derle
        uses: gradle/actions/setup-gradle@v4

      - name: APK oluştur
        run: gradle assembleDebug

      - name: APK'yı yükle
        uses: actions/upload-artifact@v4
        with:
          name: WaTaKaLauncher
          path: app/build/outputs/apk/debug/*.apk
